### ISSUE TITLE
Extend .md creation to not public member (internal, private, etc.)

### ISSUE THREAD

**Issue by dvernole** [ejball/XmlDocMarkdown#1]
As a team member I'd like to share all the reference API with other developers to help them during maintenance activities. For this reason I'd like to chose, with an option, if generate or not only public members.

**Comment by ejball** [comment]
Thanks for the feedback! Supporting `protected` is a high priority for me, but adding optional support for `internal` and `private` at the same time shouldn't be too difficult.

**Comment by ejball** [comment]
You can now use [`--visibility private`](http://ejball.com/XmlDocMarkdown/#options) to document all types and members. It doesn't have extensive testing yet, so let me know if you find bugs!

**Comment by dvernole** [comment]
Hi,
great news! We will test it very soon ;-)
_________________________________________________
Davide Vernole | CEO

Microsoft MVP Visual Studio and Development Technologies
Microsoft Certified Application Developer
Microsoft Certified Solution Developer

email: davide.vernole@adamfactory.com<mailto:davide.vernole@adamfactory.com>  | Mobile: +39.335.243456
Website: http://www.adamfactory.com<http://www.adamfactory.com/> | Blog: http://blog.knodev.com<http://blog.knodev.com/>

On 17 Mar 2017, at 17:36, Ed Ball <notifications@github.com<mailto:notifications@github.com>> wrote:


You can now use --visibility private<http://ejball.com/XmlDocMarkdown/#options> to document all types and members. It doesn't have extensive testing yet, so let me know if you find bugs!

**Comment by ejball** [comment]
Great! I did notice that the summary page is showing internal types as public types, so that will be my next fix. #3
