### ISSUE TITLE
Global tool does not run on a net5.0-only machine

### ISSUE THREAD

**Issue by SteveGilham** [ejball/XmlDocMarkdown#105]
Attempting to do so gives
```
No compatible framework version

The framework 'Microsoft.NETCore.App', version '3.1.0' was not found.

  - The following frameworks were found:

      5.0.0 at [/usr/share/dotnet/shared/Microsoft.NETCore.App]

You can resolve the problem by installing the specified framework and/or SDK.
```

A build-time work-around is to add a file `runtimeconfig.template.json` to the executable project with content
```
{
  "rollForwardOnNoCandidateFx": 2
}
```
which roughly says "this application is expected to be forward compatible"

**Comment by ejball** [comment]
I've [added](https://github.com/ejball/XmlDocMarkdown/commit/6f3095a0380a87941f66ec65027033a93f44ebae) the newer [`<RollForward>Major</RollForward>`](https://natemcmaster.com/blog/2019/01/09/netcore-primitives-3/#automatically-run-on-higher-versions) property to the project and deployed it as 2.3.1. Hopefully that fixes it!
