### ISSUE TITLE
Can't run with Uwp assemblies

### ISSUE THREAD

**Issue by KusiTec** [ejball/XmlDocMarkdown#107]
If i try to run with a Uwp dll, results the follow error message in the command prompt:

System.BadImageFormatException

Is there a way to work with Uwp dll?

**Comment by ejball** [comment]
To avoid issues like that, I've taken to building a simple app that uses the core XmlDocMarkdown library, directly references the project for which I want to generate documentation, and builds the app with a compatible target framework. I then run the app in the same way I would normally run the standard XmlDocMarkdown tool. This should prevent the errors that can occur when loading the assembly.

I hope to document the technique in the future, but here's an example [project file](https://github.com/ejball/ArgsReading/blob/master/tools/XmlDocGen/XmlDocGen.csproj) and [C# file](https://github.com/ejball/ArgsReading/blob/master/tools/XmlDocGen/XmlDocGenApp.cs). I've never tried it with a UWP assembly, but it seems like it should work.

**Comment by KusiTec** [comment]
Thanks Ed for the fast answer. In the between time I started to work with docFx. Maybe I come back to XmlDocMarkdown, then i check the examples. Greets.
