### ISSUE TITLE
Remove assembly summary statement.

### ISSUE THREAD

**Issue by ddunkin** [ejball/XmlDocMarkdown#11]
The assembly summary contains a count of types and namespaces. This could create merge conflicts for branches that change the number of types. Consider removing it.

E.g.: https://github.com/Faithlife/FaithlifeUtility/pull/8/files#diff-b27f51ccd58cc0b550053fdb6e747a7cR3

**Comment by ejball** [comment]
Good point.

**Comment by ejball** [comment]
Fixed in a7f1db82d0cdb3ee78230eca7986952d08f420d4.
