### ISSUE TITLE
Update documentation to mention that an Output File of API Documentation is required

### ISSUE THREAD

**Issue by DP-Technology-LLC** [ejball/XmlDocMarkdown#130]
Because idiots like me exist, it might be worth mentioning it.

I am in process of creating my first public code library.  I have documented code files before, but those libraries were always for internal use and those libraries were always referenced by code so never needed an Output File of API documentation.

When I got everything set up to run xmldocmd successfully, all my markdown files had, but not limited to, no descriptions and no parameters listed for methods, even though everything was thoroughly documented in the code files.

Once that Output File was created after rebuilding the project, running xmldocmd then generated all of the missing information.

**Comment by ejball** [comment]
Great idea, thanks!
