### ISSUE TITLE
XmlDocMarkdown.csproj contains unnecessary section

### ISSUE THREAD

**Issue by Jericho** [ejball/XmlDocMarkdown#29]
XmlDocMarkdown.csproj contains the following section which, as far as I can tell, serves no purpose at all:
```
<ItemDefinitionGroup>
    <PackageReference>
    <PrivateAssets>all</PrivateAssets>
  </PackageReference>
  <ProjectReference>
    <PrivateAssets>all</PrivateAssets>
  </ProjectReference>
</ItemDefinitionGroup>
```

Visual Studio seems to be be able to ignore this useless section, however it's causing the project parser in `Cake.Incubator` to throw `ArgumentNullException` when we attempt to parse the content of this project file.

The cake-contrib organization has an automated process that disocvers and audits all addins to check if they follow best practices, reference latest version of cake DLLs, etc. Unfortunately, this issue is preventing the automated process to audit the Cake.XmlDocMarkdown addin. 

I suggest removing this `ItemDefinitionGroup` section which, hopefully, will allow the automated process to audit your addin.

**Comment by ejball** [comment]
@Jericho, that section is equivalent to putting `PrivateAssets="All"` on each reference, which I've done instead.
