### ISSUE TITLE
Recommended changes resulting from automated audit

### ISSUE THREAD

**Issue by Jericho** [ejball/XmlDocMarkdown#31]
We performed an automated audit of your Cake addin and found that it does not follow all the best practices.

We encourage you to make the following modifications:

- [ ] You are currently referencing Cake.Core 0.27.1. Please upgrade to 0.28.0
- [ ] The Cake.Core reference should be private. Specifically, your addin's `.csproj` should have a line similar to this: `<PackageReference Include="Cake.Core" Version="0.28.0" PrivateAssets="All" />`
- [ ] Your addin should target netstandard2.0. Please note that there is no need to multi-target, netstandard2.0 is sufficient.
- [ ] The nuget package for your addin should use the cake-contrib icon. Specifically, your addin's `.csproj` should have a line like this: `<PackageIconUrl>https://cdn.rawgit.com/cake-contrib/graphics/a5cf0f881c390650144b2243ae551d5b9f836196/png/cake-contrib-medium.png</PackageIconUrl>`.

Apologies if this is already being worked on, or if there are existing open issues, this issue was created based on what is currently published for this package on NuGet.org and in the project on github.

**Comment by ejball** [comment]
@Jericho, the first two items are fixed.

The other two items are not an issue. Perhaps the audit looked at the wrong project.

Are these best practices documented somewhere?

**Comment by Jericho** [comment]
Some of the guidelines are documented [here](https://github.com/cake-contrib/Home/blob/master/Guidelines.md) but it seems this document hasn't been updated in quite some time is is not completely up to date. For instance, it refers to Cake 0.22.0 as being the must recent version and it also talks about IL merging dependncines into your addin which is no longer necessary.

As for the best practices audited by the automated process, they are documented in the generated [report](https://github.com/cake-contrib/Home/blob/master/Audit.md).

**Comment by Jericho** [comment]
Also, when you say "the other two items are not an issue" do you mean that you don't agree with the recommendations or that your addin is following these recommandations and the audit process is incorrectly flagging?
