### ISSUE TITLE
System.TypeLoadException 

### ISSUE THREAD

**Issue by jzeferino** [ejball/XmlDocMarkdown#32]
I'm calling `XmlDocMarkdownGenerate` in Cake with a Xamarin.iOS library dll.
It throws the following exception:

`System.TypeLoadException: Could not load method 22 due to Could not load file or assembly 'Xamarin.iOS, Version=0.0.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065' or one of its dependencies.`

1 - How can I add dependent assemblies?

2 - There is any way of generating the documentation from source code instead of .dll?

**Comment by ejball** [comment]
1. The tool calls `Assembly.LoadFrom` on the assembly. Unfortunately there is no way to add additional assemblies other than however .NET loads them.

2. This tool cannot generate documentation from the source code.

**Comment by jzeferino** [comment]
Ended up adding dependent assemblies manually and get around with it.
