### ISSUE TITLE
Error generating docs when assembly depends from Newtonsoft.Json

### ISSUE THREAD

**Issue by sungam3r** [ejball/XmlDocMarkdown#36]
If I generate documentation for an assembly (I use Global Tool) that refers to an Newtonsoft.Json version other than 11.0.1 I get following error:
```
System.IO.FileLoadException: Could not load file or assembly 'Newtonsoft.Json, Version=12.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'. Could not find or load a specific file. (Exception from HRESULT: 0x80131621)
File name: 'Newtonsoft.Json, Version=12.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' ---> System.IO.FileLoadException: Could not load file or assembly 'Newtonsoft.Json, Version=12.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'.
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyLoadContext, String ilPath, String niPath, ObjectHandleOnStack retAssembly)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
   at System.Reflection.Assembly.LoadFrom(String assemblyFile)
   at System.Reflection.Assembly.LoadFromResolveHandler(Object sender, ResolveEventArgs args)
   at System.AppDomain.InvokeResolveEvent(ResolveEventHandler eventHandler, RuntimeAssembly assembly, String name)
```

This happens because version 11 is already loaded into the domain.

**Comment by sungam3r** [comment]
Current workaround - I updated Newtonsoft.Json to 12.0.2, updated xmldocmd to new preview version and installed it on the machine. It is clear that for other versions this change will not work. Ideally, you should stop using Newtonsoft.Json at all for parsing settings.

**Comment by ejball** [comment]
Thanks for the report! I'm glad you found a workaround.

I'm a bit tempted to drop support for `--settings`, since I never ended up using it, and I'm not excited to parse JSON without Json.NET...

**Comment by sungam3r** [comment]
You can always find a solution - [ILMerge](https://github.com/dotnet/ILMerge) to the rescue!

**Comment by sungam3r** [comment]
I saw that you removed the dependency, so I close the issue.
