### ISSUE TITLE
Add a file version

### ISSUE THREAD

**Issue by lovettchris** [ejball/XmlDocMarkdown#62]
Can you add a file version either to the assembly on disk, or to the help output, so that I can automate upgrading the tool to a specific version?  Notice there is no file version on this command line:
```
d:\git\foundry99\Coyote>filever d:\git\foundry99\Coyote\packages\xmldocmd.exe
--a-- W32x64   -   -               -   -    137,728 02-19-2020 xmldocmd.exe
```

and here:
![image](https://user-images.githubusercontent.com/18707114/74870199-31e59b00-530e-11ea-9f4c-45023980a7c5.png)

**Comment by ejball** [comment]
Where did that `xmldocmd.exe` come from? The file in my `.dotnet\tools` directory (after running `dotnet tool install xmldocmd -g`) has a file version as expected.

Generally speaking, `dotnet tool` is used to install and update `xmldocmd`, which uses NuGet versioning, not file or assembly versions.

**Comment by lovettchris** [comment]
It is the program that was installed by using "dotnet tool install -g xmldocmd".  it might be as simple as adding this to the xmldocmd.csproj?
```
<Version>2.1.0</Version>
```

**Comment by bgrainger** [comment]
When I run `dotnet tool install -g xmldocmd` it installs version 2.0.2.184 into `%USERPROFILE%\.dotnet\tools` (and all the file version information is present).

How are you ending up with a copy of the EXE in `d:\git\foundry99\Coyote\packages`?

**Comment by lovettchris** [comment]
Oh, right, that's just using the --tool-path option instead of -g.  But dotnet knows the version if you run "dotnet tool list --g", so I can use this for now if you don't want to fix the assembly/file version.

**Comment by bgrainger** [comment]
The latest version of xmldocmd.exe is 170,496 bytes; is it possible you just have a very old version installed (that's lacking version information). 

>  if you don't want to fix the assembly/file version

Running `dotnet tool install -g xmldocmd` installs a version that contains file version information. I'm not sure what there is to fix.

![image](https://user-images.githubusercontent.com/188129/75061931-96336680-5496-11ea-90dc-62340d4ebd0b.png)

**Comment by lovettchris** [comment]
How strange, when I do this:
```
dotnet tool uninstall xmldocmd -g
dotnet tool install xmldocmd -g
```
I see the file in C:\Users\Chris\.dotnet\tools\ has no version info -- File version is blank...

Perhaps the difference is the version of dotnet I'm using which is 2.2.402.  What do you use ?

**Comment by bgrainger** [comment]
I'm using 3.1.100. .NET Core 2.2 is EOL (https://dotnet.microsoft.com/platform/support/policy/dotnet-core#lifecycle) so I'd recommend updating to 3.1 (LTS).

**Comment by lovettchris** [comment]
Ok, thanks, I'll close this item then.
