### ISSUE TITLE
Fails when using .net core / standard and external packages

### ISSUE THREAD

**Issue by winterscr** [ejball/XmlDocMarkdown#69]
Since .net core/standard do not copy NuGet dependencies to the output folder xml doc comments that reference items from external dependencies pulled in by packages are not found by the tool when generating the documentation as appears to only be resolving the assemblies from the output folder.

I can currently work around this with a build step that copies the missing DLLs from the %USERPROFILE%\.nuget\packages folder to the output folder but ideally the tool should check there to resolve assembly dependencies.

**Comment by winterscr** [comment]
This might be the same issue as #68 but I've raised it as a separate issue as it's more general and I'm not 100% sure it's the same issue.

**Comment by winterscr** [comment]
I've confirmed this is the same issue as #68, copying the references assemblies for `Microsoft.AspNetCore.App` from `%ProgramW6432%\dotnet\shared\...` lets the documentation build. That path should probably also be added for assembly resolution.

Possibly a new command line argument to add extra paths.

**Comment by sungam3r** [comment]
@winterscr Why not just call `dotnet publish` ?

**Comment by winterscr** [comment]
Unfortunately two reasons.
1. `dotnet publish` doesn't copy framework assemblies like `Microsoft.AspNetCore.Core.dll` into `bin` unless you specify `--self-contained` and `--runtime` with a target runtime. I'd rather not do this as the target runtime environment could be either Linux or Windows and I don't want to specify and have two builds, or make it self-contained since all of our servers have the frameworks installed already.
2. Some of the projects are NuGet packages, as such they're not published using `dotnet publish` but built and packed with NuGet dependencies pulled in as packages and loaded from the global package cache. I want to build SDK documentation and upload it to our team wiki as part of the package build.

I could indeed do a `dotnet publish` for both of these scenarios but it would be wasteful to do that when in scenario 1 it wouldn't work without additional unwanted flags and in scenario 2 just isn't necessary for the build process.

My current workaround is working ok for now but it would be nice to not have to copy unneeded DLLs into the bin folder either through a `dotnet publish` or a MSBuild copy task.

**Comment by sungam3r** [comment]
Strange, I also use external dependencies in many of my packages, but I did not encounter the described problem. I do not specify `--self-contained` and `--runtime`, just `dotnet publish`.

> Some of the projects are NuGet packages, as such they're not published using dotnet publish but built and packed with NuGet dependencies pulled in as packages and loaded from the global package cache. I want to build SDK documentation and upload it to our team wiki as part of the package build.

So do I but I explicitly do `dotnet publish` for libs packages after build. It is just one more step in CI for generating docs. `dotnet publish` copies all external deps in output folder - System.*, Microsoft.* (including AspNetCore) and so on.

![изображение](https://user-images.githubusercontent.com/21261007/79672386-1eee2a80-81da-11ea-8e01-29857b980c9c.png)

**Comment by winterscr** [comment]
I think it might be related to the change with AspNetCore no longer being NuGet packages. Some of the components still are and they do get copied into the publish folder, however the core dlls are now part of the framework when you add the `Microsoft.AspNetCore.App` framework reference to the project so they don’t get copied in unless you do a self contained publish to pull in the framework dlls.

I’ll have another play in the morning and double check it but I’m guessing your NuGet packages aren’t extending and returning the types in the core AspNetCore framework assemblies.

I’d still rather avoid unnecessary file copying if I can, I’ve forked the repo and if I get chance I’ll have a look at the assembly loading and see if I can get it to check the global NuGet package cache and DotNetCore shared assembly folders too. It would be useful to me at least to do that.

**Comment by sungam3r** [comment]
Maybe.

> I’ll have a look at the assembly loading and see if I can get it to check the global NuGet package cache and DotNetCore shared assembly folders too. It would be useful to me at least to do that.

Of course, this feature will be useful in any case.

**Comment by ejball** [comment]
Thanks, @winterscr, for filing this issue, and thanks @sungam3r for suggesting a workaround. External dependencies are a real sticking point with this tool; I wish I had the time to pursue other strategies.

**Comment by ejball** [comment]
For what it's worth, my latest solution to the dependency problem is to build a custom console app that works the same way as `xmldocmd` but directly includes the assembly references that I need. I've made this as easy as possible with version `2.3.0` of the `XmlDocMarkdown.Core`. For example, here is the project file and source code that I use with the `ArgsReading` library:

* https://github.com/ejball/ArgsReading/blob/master/tools/XmlDocGen/XmlDocGen.csproj
* https://github.com/ejball/ArgsReading/blob/master/tools/XmlDocGen/XmlDocGenApp.cs

Then I just run `XmlDocGen` the same way that I would run `xmldocmd`, except that it also supports an assembly name as input, e.g. instead of passing the assembly path `ArgsReading.dll`, I just pass the assembly name `ArgsReading` and it uses the assembly that's already loaded into the custom console app.

**Comment by winterscr** [comment]
I've got some code working using a custom assembly resolver to load from the nuget package cache, I'm still working on it but it's been a very busy few months at work so I've not been able to spend much time on it.

I'll see if I can get a bit of time over the next few weeks and get something to PR.

**Comment by ejball** [comment]
I have [updated the documentation](https://ejball.com/XmlDocMarkdown/) to recommend building a custom console app to avoid issues when loading the assembly.

**Comment by thomasnal** [comment]
Hi, I experience the xmldocmd issue with resolving the depedencies - The system cannot find the file specified.  xmldocmd is not able to resolve dependencies installed as nuget packages.

XmlDocMarkdown is supposed to solve the issue.  It is nowhere instructted how to install this tool.  The `dotnet tool install XmlDocMarkdown --globa` fails with  `error NU1212: Invalid project-package combination for XmlDocMarkdown 2.9.0.`.

Has this issue been resolved in anyway?

**Comment by thomasnal** [comment]
```
$ nuget install XmlDocMarkdown -excludeversion
$ ls XmlDocMarkdown/
XmlDocMarkdown.nupkg tools
$ ls XmlDocMarkdown/tools/
XmlDocMarkdown.Core.dll XmlDocMarkdown.exe
$ dotnet tool run XmlDocMarkdown
Cannot find a tool in the manifest file that has a command named 'XmlDocMarkdown
```

**Comment by ejball** [comment]
[Per the docs](https://ejball.com/XmlDocMarkdown/#usage), the most reliable way to use XmlDocMarkdown is to build and run a command-line tool that references the XmlDocMarkdown.Core class library and the assembly that you want to document. This ensures that the assembly and all of its dependencies are loaded properly.

There are links that demonstrate how to do this. Have you been able to try that approach?

**Comment by thomasnal** [comment]
I've got that working after I got more understanding of Assembly.LoadFrom issues and what the usage section wants to say.  I would just add the csproj and cs file inline and say do it this way.  But now when I understand it, I am good.

**Comment by ejball** [comment]
Thanks, that's a good idea.
